/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HmacSigner {
  constructor(key: Uint8Array)
  sign(data: Buffer): Buffer
  verify(data: Buffer, sig: Buffer): boolean
}

export declare class Ingress {
  constructor(options: IngressOptions)
  /**
   * Optimized entrypoint for Bun 1.4.
   *
   * Meta format (unchanged):
   *   [u16 method_len][method]
   *   [u32 url_len][url]
   *   [u16 socket_ip_len][socket_ip]
   *   [u32 packed_headers_len][packed_headers]
   *
   * Output format v3 (BREAKING — smaller, no redundant data):
   *   [u8 version=3]
   *   [u8 verdict]
   *   [u16 status]
   *   [u32 flags]
   *   [u64 cache_key]
   *   [u32 request_id_len][request_id]
   *   [u32 trace_id_len][trace_id]
   *   [u32 span_id_len][span_id]
   *   [u32 rate_remaining]
   *   [u64 rate_reset_ms]
   *   [u32 response_headers_count]
   *   repeated: [u32 name_len][name][u32 value_len][value]
   *   [u32 cookies_len][cookies_packed]
   *   [u32 query_len][query_packed]
   *   [u32 error_body_len][error_body]
   *
   * REMOVED from output (JS already has these):
   *   - path (JS has req.url)
   *   - raw_query (JS has req.url)
   *   - body (JS owns it, never echoed)
   */
  handlePacked(meta: Uint8Array, body: Uint8Array | null): Buffer
}

export declare class SchemaValidator {
  constructor(schemaBytes: Uint8Array)
  /**
   * Validate a packed batch of individual JSON documents.
   *
   * Input format:
   *
   *   [u32 count]
   *   repeated:
   *     [u32 doc_len]
   *     [doc bytes]
   *
   * This avoids materializing the entire batch into one DOM array.
   */
  validateBatchPackedCount(packed: Uint8Array): number
  /**
   * Validate a packed batch and return a packed bitset.
   *
   * Output format:
   *
   *   [u32 count]
   *   [ceil(count / 8) bytes]
   */
  validateBatchPackedBitset(packed: Uint8Array): Buffer
  /**
   * Stream-validate a JSON array payload.
   *
   * This still materializes one array element at a time, because
   * `jsonschema` currently expects a DOM-like value, but it avoids
   * materializing the entire array at once.
   */
  validateBatchStreaming(batchBytes: Uint8Array): number
}

export declare function cookieParseBatchPacked(input: Uint8Array): Buffer

export declare function cookieParseBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function cookieParsePacked(input: Uint8Array): Buffer

export declare function cookieParsePackedInto(input: Uint8Array, output: Uint8Array): number

export interface CorsOptions {
  allowOrigin?: Array<string>
  allowMethods?: Array<string>
  allowHeaders?: Array<string>
  exposeHeaders?: Array<string>
  allowCredentials?: boolean
  maxAge?: number
}

export declare function crc32(input: Uint8Array): number

/**
 * Packed batch CRC32.
 *
 * Input format:
 *   [u32 count]
 *   repeated:
 *     [u32 len]
 *     [bytes]
 *
 * Output format:
 *   [u32 count]
 *   repeated:
 *     [u32 crc]
 */
export declare function crc32BatchPacked(input: Uint8Array): Buffer

export declare function fnv1a64(input: Uint8Array): bigint

export declare function hmacSha256(key: Uint8Array, data: Buffer): Buffer

export declare function hmacSha256Verify(key: Uint8Array, data: Buffer, sig: Buffer): boolean

export declare function httpParseRequestBatchPacked(input: Uint8Array): Buffer

export declare function httpParseRequestBatchPackedAsync(input: Uint8Array): Promise<Buffer>

/**
 * Allocating packed parser.
 *
 * This still allocates the output buffer, but it does not allocate
 * a HashMap, header Strings, or JSON DOM nodes.
 */
export declare function httpParseRequestPacked(input: Uint8Array): Buffer

/**
 * Zero-output-allocation packed parser.
 *
 * JS provides the output buffer. Rust writes directly into it.
 *
 * In Bun/Node, the typed array is a view over shared memory, so this
 * avoids an extra Rust-to-JS copy of the final result.
 */
export declare function httpParseRequestPackedInto(input: Uint8Array, output: Uint8Array): number

export interface IngressOptions {
  trustProxy?: boolean
  parseCookies?: boolean
  parseQuery?: boolean
  requireJsonBody?: boolean
  schema?: Uint8Array
  cors?: CorsOptions
  rateLimit?: RateLimitOptions
  security?: SecurityHeadersOptions
  https?: boolean
  maxBodyBytes?: number
  enableSecurityHeaders?: boolean
  enableRequestIds?: boolean
  enableCacheKey?: boolean
  enablePathQuery?: boolean
  enableBodySizeGuard?: boolean
}

/** Call once at application startup if you want a custom Rayon thread count. */
export declare function initThreadPool(rayonThreads?: number | undefined | null): void

export declare function jsonPatch(doc: Uint8Array, patch: Uint8Array): Buffer

export declare function jsonSumBatchPacked(input: Uint8Array): Buffer

export declare function jsonSumBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function jsonSumIds(input: Uint8Array): number

export declare function jsonSumIdsAsync(input: Uint8Array): Promise<number>

export declare function jsonValid(input: Uint8Array): boolean

export declare function jsonValidAsync(input: Uint8Array): Promise<number>

export declare function jsonValidBatchPacked(input: Uint8Array): Buffer

export declare function jsonValidBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function mimeFromExtension(ext: Uint8Array): Buffer

export declare function queryParseBatchPacked(input: Uint8Array): Buffer

export declare function queryParseBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function queryParsePacked(input: Uint8Array): Buffer

export declare function queryParsePackedInto(input: Uint8Array, output: Uint8Array): number

export declare function randomToken(byteLen: number): Buffer

export interface RateLimitOptions {
  limit?: number
  windowMs?: number
}

export declare function rayonNumThreads(): number

export interface SecurityHeadersOptions {
  contentSecurityPolicy?: string
  hsts?: boolean
  hstsMaxAge?: number
  hstsIncludeSubdomains?: boolean
  hstsPreload?: boolean
  frameOptions?: string
  nosniff?: boolean
  referrerPolicy?: string
  coep?: string
  coop?: string
  corp?: string
  xssProtection?: string
}

export declare function urlDecode(input: Uint8Array): Buffer

export declare function urlDecodeBytes(input: Uint8Array): Buffer

export declare function urlDecodeInto(input: Uint8Array, output: Uint8Array): number

export declare function urlEncode(input: Uint8Array): Buffer

export declare function urlEncodeInto(input: Uint8Array, output: Uint8Array): number

export declare function validateEmail(input: Uint8Array): boolean

export declare function validateEmailBatchPacked(input: Uint8Array): Buffer

export declare function validateEmailBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateIpv4(input: Uint8Array): boolean

export declare function validateIpv4BatchPacked(input: Uint8Array): Buffer

export declare function validateIpv4BatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateIpv6(input: Uint8Array): boolean

export declare function validateIpv6BatchPacked(input: Uint8Array): Buffer

export declare function validateIpv6BatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateUuid(input: Uint8Array): boolean

export declare function validateUuidBatchPacked(input: Uint8Array): Buffer

export declare function validateUuidBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function wsAcceptKey(key: Uint8Array): Buffer
