/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HmacSigner {
  constructor(key: Uint8Array)
  sign(data: Buffer): Buffer
  verify(data: Buffer, sig: Buffer): boolean
}

export declare class Ingress {
  constructor(options: IngressOptions)
  handleRequest(method_kind: number, url: Uint8Array, ip: Uint8Array, request_id: Uint8Array, headers: Uint8Array, body: Uint8Array | null, output: Uint8Array): number
}

export declare class SchemaValidator {
  constructor(schemaBytes: Uint8Array)
  /**
   * Validate a packed batch of individual JSON documents.
   *
   * Input format:
   *
   *   [u32 count]
   *   repeated:
   *     [u32 doc_len]
   *     [doc bytes]
   *
   * This avoids materializing the entire batch into one DOM array.
   */
  validateBatchPackedCount(packed: Uint8Array): number
  /**
   * Validate a packed batch and return a packed bitset.
   *
   * Output format:
   *
   *   [u32 count]
   *   [ceil(count / 8) bytes]
   */
  validateBatchPackedBitset(packed: Uint8Array): Buffer
  /**
   * Stream-validate a JSON array payload.
   *
   * This still materializes one array element at a time, because
   * `jsonschema` currently expects a DOM-like value, but it avoids
   * materializing the entire array at once.
   */
  validateBatchStreaming(batchBytes: Uint8Array): number
}

export declare function cookieParseBatchPacked(input: Uint8Array): Buffer

export declare function cookieParseBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function cookieParseBatchTotalLenPacked(input: Uint8Array): number

export declare function cookieParsePacked(input: Uint8Array): Buffer

export declare function cookieParsePackedInto(input: Uint8Array, output: Uint8Array): number

export interface CorsOptions {
  allowOrigin?: Array<string>
  allowMethods?: Array<string>
  allowHeaders?: Array<string>
  exposeHeaders?: Array<string>
  allowCredentials?: boolean
  maxAge?: number
}

export declare function crc32(input: Uint8Array): number

/**
 * Packed batch CRC32.
 *
 * Input format:
 *   [u32 count]
 *   repeated:
 *     [u32 len]
 *     [bytes]
 *
 * Output format:
 *   [u32 count]
 *   repeated:
 *     [u32 crc]
 */
export declare function crc32BatchPacked(input: Uint8Array): Buffer

export declare function fnv1a64(input: Uint8Array): bigint

export declare function hmacSha256(key: Uint8Array, data: Buffer): Buffer

export declare function hmacSha256Verify(key: Uint8Array, data: Buffer, sig: Buffer): boolean

export declare function httpParseRequestBatchPacked(input: Uint8Array): Buffer

export declare function httpParseRequestBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function httpParseRequestBatchTotalLenPacked(input: Uint8Array): number

export declare function httpParseRequestPacked(input: Uint8Array): Buffer

export declare function httpParseRequestPackedInto(input: Uint8Array, output: Uint8Array): number

export interface IngressOptions {
  trustProxy?: boolean
  parseCookies?: boolean
  parseQuery?: boolean
  requireJsonBody?: boolean
  schema?: Uint8Array
  cors?: CorsOptions
  rateLimit?: RateLimitOptions
  https?: boolean
  maxBodyBytes?: number
  enableBodySizeGuard?: boolean
}

export declare function initThreadPool(rayonThreads?: number | undefined | null): void

export declare function jsonPatch(doc: Uint8Array, patch: Uint8Array): Buffer

export declare function jsonSumBatchPacked(input: Uint8Array): Buffer

export declare function jsonSumBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function jsonSumBatchTotalPacked(input: Uint8Array): number

export declare function jsonSumIds(input: Uint8Array): number

export declare function jsonSumIdsAsync(input: Uint8Array): Promise<number>

export declare function jsonValid(input: Uint8Array): boolean

export declare function jsonValidAsync(input: Uint8Array): Promise<number>

export declare function jsonValidBatchCountPacked(input: Uint8Array): number

export declare function jsonValidBatchPacked(input: Uint8Array): Buffer

export declare function jsonValidBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function mimeFromExtension(ext: Uint8Array): Buffer

export declare function queryParseBatchPacked(input: Uint8Array): Buffer

export declare function queryParseBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function queryParseBatchTotalLenPacked(input: Uint8Array): number

export declare function queryParsePacked(input: Uint8Array): Buffer

export declare function queryParsePackedInto(input: Uint8Array, output: Uint8Array): number

export declare function randomToken(byteLen: number): Buffer

export interface RateLimitOptions {
  limit?: number
  windowMs?: number
}

export declare function rayonNumThreads(): number

export declare function urlDecode(input: Uint8Array): Buffer

export declare function urlDecodeBytes(input: Uint8Array): Buffer

export declare function urlDecodeInto(input: Uint8Array, output: Uint8Array): number

export declare function urlEncode(input: Uint8Array): Buffer

export declare function urlEncodeInto(input: Uint8Array, output: Uint8Array): number

export declare function validateEmail(input: Uint8Array): boolean

export declare function validateEmailBatchCountPacked(input: Uint8Array): number

export declare function validateEmailBatchPacked(input: Uint8Array): Buffer

export declare function validateEmailBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateIpv4(input: Uint8Array): boolean

export declare function validateIpv4BatchCountPacked(input: Uint8Array): number

export declare function validateIpv4BatchPacked(input: Uint8Array): Buffer

export declare function validateIpv4BatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateIpv6(input: Uint8Array): boolean

export declare function validateIpv6BatchCountPacked(input: Uint8Array): number

export declare function validateIpv6BatchPacked(input: Uint8Array): Buffer

export declare function validateIpv6BatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateUuid(input: Uint8Array): boolean

export declare function validateUuidBatchCountPacked(input: Uint8Array): number

export declare function validateUuidBatchPacked(input: Uint8Array): Buffer

export declare function validateUuidBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function wsAcceptKey(key: Uint8Array): Buffer
