/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Async ingress handler.
 * Accepts raw request components, processes on thread pool, returns output buffer.
 * This eliminates the synchronous napi blocking by offloading to tokio's blocking pool.
 */
export declare class AsyncIngress {
  constructor(options: IngressOptions)
  /**
   * Async ingress handler.
   * Accepts raw request components, processes on tokio blocking thread pool.
   *
   * @param methodKind - numeric method kind (0=GET, 1=HEAD, ..., 6=OPTIONS)
   * @param url - request URL string
   * @param ip - client IP string (or "0.0.0.0")
   * @param requestId - request ID hex string
   * @param headers - Array<[name: string, value: string]>
   * @param body - Uint8Array | null
   * @param outputBufferSize - size of output buffer to allocate (default 262144)
   * @returns Uint8Array containing the output header + metadata JSON
   */
  handleRequestFull(methodKind: number, url: string, ip: string, requestId: string, headers: Array<[string, string]>, body: Uint8Array | null, outputBufferSize?: number): Promise<Uint8Array>
}

export declare class HmacSigner {
  constructor(key: Uint8Array)
  sign(data: Buffer): Buffer
  verify(data: Buffer, sig: Buffer): boolean
}

export declare class Ingress {
  constructor(options: IngressOptions)
  /**
   * Production API:
   *   input = packed metadata frame
   *   body = separate zero-copy body
   *   output = response decision buffer
   */
  handleRequestPacked(input: Uint8Array, body: Uint8Array | null, output: Uint8Array): number
  /**
   * Optimized sync API:
   * Accepts raw JS values (no binary packing in JS), packs them in Rust,
   * processes synchronously (no tokio thread pool overhead).
   * This is the fastest path for simple requests.
   */
  handleRequestFullSync(methodKind: number, url: string, ip: string, requestId: string, headers: Array<[string, string]>, body: Uint8Array | null, outputBufferSize?: number): Uint8Array
}

export declare class SchemaValidator {
  constructor(schemaBytes: Uint8Array)
  /**
   * Validate a packed batch of individual JSON documents.
   *
   * Input format:
   *
   *   [u32 count]
   *   repeated:
   *     [u32 doc_len]
   *     [doc bytes]
   *
   * This avoids materializing the entire batch into one DOM array.
   */
  validateBatchPackedCount(packed: Uint8Array): number
  /**
   * Validate a packed batch and return a packed bitset.
   *
   * Output format:
   *
   *   [u32 count]
   *   [ceil(count / 8) bytes]
   */
  validateBatchPackedBitset(packed: Uint8Array): Buffer
  /**
   * Stream-validate a JSON array payload.
   *
   * This still materializes one array element at a time, because
   * `jsonschema` currently expects a DOM-like value, but it avoids
   * materializing the entire array at once.
   */
  validateBatchStreaming(batchBytes: Uint8Array): number
}

export declare function cookieParseBatchPacked(input: Uint8Array): Buffer

export declare function cookieParseBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function cookieParseBatchTotalLenPacked(input: Uint8Array): number

export declare function cookieParsePacked(input: Uint8Array): Buffer

export declare function cookieParsePackedInto(input: Uint8Array, output: Uint8Array): number

export interface CorsOptions {
  allowOrigin?: Array<string>
  allowMethods?: Array<string>
  allowHeaders?: Array<string>
  exposeHeaders?: Array<string>
  allowCredentials?: boolean
  maxAge?: number
}

export declare function crc32(input: Uint8Array): number

/** CRC32 batch — zero-alloc inline iteration (no Vec allocation from unpack). */
export declare function crc32BatchPacked(input: Uint8Array): Buffer

export declare function fnv1a64(input: Uint8Array): bigint

export declare function hmacSha256(key: Uint8Array, data: Buffer): Buffer

export declare function hmacSha256Verify(key: Uint8Array, data: Buffer, sig: Buffer): boolean

export declare function httpParseRequestBatchPacked(input: Uint8Array): Buffer

export declare function httpParseRequestBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function httpParseRequestBatchTotalLenPacked(input: Uint8Array): number

export declare function httpParseRequestPacked(input: Uint8Array): Buffer

export declare function httpParseRequestPackedInto(input: Uint8Array, output: Uint8Array): number

export const INGRESS_ERR_BAD_REQUEST: number

export const INGRESS_ERR_BODY_TOO_LARGE: number

export const INGRESS_ERR_CORS_PREFLIGHT: number

export const INGRESS_ERR_INTERNAL: number

export const INGRESS_ERR_INVALID_JSON: number

export const INGRESS_ERR_NONE: number

export const INGRESS_ERR_RATE_LIMITED: number

export const INGRESS_ERR_REQUEST_TOO_LARGE: number

export const INGRESS_ERR_SCHEMA_VALIDATION: number

export const INGRESS_FLAG_BODY_TRUNCATED: number

export const INGRESS_FLAG_BODY_VALID_JSON: number

export const INGRESS_FLAG_CORS_ALLOWED: number

export const INGRESS_FLAG_HAS_COOKIES: number

export const INGRESS_FLAG_HAS_QUERY: number

export const INGRESS_FLAG_HTTPS: number

export const INGRESS_FLAG_IS_PREFLIGHT: number

export const INGRESS_FLAG_RATE_LIMITED: number

export const INGRESS_FLAG_SCHEMA_VALID: number

export const INGRESS_FLAG_TRUSTED_PROXY: number

export const INGRESS_HV_CORS_PREFLIGHT: number

export const INGRESS_HV_CORS_SIMPLE: number

export const INGRESS_HV_COUNT: number

export const INGRESS_HV_JSON: number

export const INGRESS_HV_RATE_ACTIVE: number

export const INGRESS_HV_RATE_LIMITED: number

export const INGRESS_OUT_BODY_JSON_LEN: number

export const INGRESS_OUT_COOKIES_JSON_LEN: number

export const INGRESS_OUT_DATA_START: number

export const INGRESS_OUT_ERROR_CODE: number

export const INGRESS_OUT_FLAGS: number

export const INGRESS_OUT_HEADER_VARIANT: number

export const INGRESS_OUT_QUERY_JSON_LEN: number

export const INGRESS_OUT_RATE_LIMIT: number

export const INGRESS_OUT_RATE_REMAINING: number

export const INGRESS_OUT_RATE_RESET: number

export const INGRESS_OUT_RETRY_AFTER: number

export const INGRESS_OUT_STATUS: number

export const INGRESS_OUT_VERDICT: number

export interface IngressLimitsOptions {
  maxUrlBytes?: number
  maxQueryBytes?: number
  maxCookieBytes?: number
  maxHeadersBytes?: number
  maxHeaders?: number
  maxPairs?: number
}

export interface IngressOptions {
  trustProxy?: boolean
  trustedProxies?: TrustedProxyOptions
  parseCookies?: boolean
  parseQuery?: boolean
  requireJsonBody?: boolean
  schema?: Uint8Array
  cors?: CorsOptions
  rateLimit?: RateLimitOptions
  https?: boolean
  maxBodyBytes?: number
  enableBodySizeGuard?: boolean
  emitMetadataJson?: boolean
  limits?: IngressLimitsOptions
}

export declare function initThreadPool(rayonThreads?: number | undefined | null): void

export declare function jsonPatch(doc: Uint8Array, patch: Uint8Array): Buffer

export declare function jsonSumBatchPacked(input: Uint8Array): Buffer

export declare function jsonSumBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function jsonSumBatchTotalPacked(input: Uint8Array): number

export declare function jsonSumIds(input: Uint8Array): number

export declare function jsonSumIdsAsync(input: Uint8Array): Promise<number>

export declare function jsonValid(input: Uint8Array): boolean

export declare function jsonValidAsync(input: Uint8Array): Promise<number>

export declare function jsonValidBatchCountPacked(input: Uint8Array): number

export declare function jsonValidBatchPacked(input: Uint8Array): Buffer

export declare function jsonValidBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function mimeFromExtension(ext: Uint8Array): Buffer

export declare function queryParseBatchPacked(input: Uint8Array): Buffer

export declare function queryParseBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function queryParseBatchTotalLenPacked(input: Uint8Array): number

export declare function queryParsePacked(input: Uint8Array): Buffer

export declare function queryParsePackedInto(input: Uint8Array, output: Uint8Array): number

export declare function randomToken(byteLen: number): Buffer

export interface RateLimitOptions {
  limit?: number
  windowMs?: number
  maxEntries?: number
}

export declare function rayonNumThreads(): number

export interface TrustedProxyOptions {
  enabled?: boolean
  networks?: Array<string>
}

export declare function urlDecode(input: Uint8Array): Buffer

export declare function urlDecodeBytes(input: Uint8Array): Buffer

export declare function urlDecodeInto(input: Uint8Array, output: Uint8Array): number

export declare function urlEncode(input: Uint8Array): Buffer

export declare function urlEncodeInto(input: Uint8Array, output: Uint8Array): number

export declare function validateEmail(input: Uint8Array): boolean

export declare function validateEmailBatchCountPacked(input: Uint8Array): number

export declare function validateEmailBatchPacked(input: Uint8Array): Buffer

export declare function validateEmailBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateIpv4(input: Uint8Array): boolean

export declare function validateIpv4BatchCountPacked(input: Uint8Array): number

export declare function validateIpv4BatchPacked(input: Uint8Array): Buffer

export declare function validateIpv4BatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateIpv6(input: Uint8Array): boolean

export declare function validateIpv6BatchCountPacked(input: Uint8Array): number

export declare function validateIpv6BatchPacked(input: Uint8Array): Buffer

export declare function validateIpv6BatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function validateUuid(input: Uint8Array): boolean

export declare function validateUuidBatchCountPacked(input: Uint8Array): number

export declare function validateUuidBatchPacked(input: Uint8Array): Buffer

export declare function validateUuidBatchPackedAsync(input: Uint8Array): Promise<Buffer>

export declare function wsAcceptKey(key: Uint8Array): Buffer
