import * as native from "../baseline";
import { decoder, encoder } from "../shared/bytes";
import { createRawRustClient } from "./raw";
import { createFfiRuntime, type FfiRuntime } from "./runtime";

/**
 * Optimized public client.
 *
 * This starts from the raw Rust FFI client, then overrides individual methods
 * with native Bun/JavaScript implementations when benchmarks prove native is
 * faster for the practical workload.
 */
export function createRustClient(runtime: FfiRuntime = createFfiRuntime()) {
  const client = createRawRustClient(runtime);

  // AUTO-GENERATED by scripts/optimize.py.
  // Fastest implementation selected by benchmark measurement.
  client.randomToken = (byteLen: number): Uint8Array => native.nativeRandomToken(byteLen);
  client.jsonPatch = (doc: Uint8Array, patch: Uint8Array): Uint8Array => native.nativeJsonPatch(doc, patch);
  client.hmacSha256 = (key: Uint8Array, data: Uint8Array): Uint8Array => native.nativeHmacSha256(key, data);
  client.mimeFromExtension = (ext: Uint8Array): Uint8Array => encoder.encode(native.nativeMimeFromExtension(decoder.decode(ext)));
  client.urlEncode = (bytes: Uint8Array): Uint8Array => encoder.encode(native.nativeUrlEncode(bytes));
  client.urlDecode = (bytes: Uint8Array): Uint8Array => encoder.encode(native.nativeUrlDecode(bytes));

  return client;
}

export type RustClient = ReturnType<typeof createRustClient>;
export const rust = createRustClient();
