//! # Selection — which ops the public API should back with native vs TS code.
//!
//! This is the SINGLE SOURCE OF TRUTH for the native-vs-TS decision, owned by
//! the castrum library itself (not by consumers). It is **auto-selected by the
//! benchmark script**: `scripts/select-native.ts` measures the addon against a
//! representative pure-TS implementation for every op on the target machine and
//! writes the winning implementation to `src/selection.json` (committed,
//! generated — NOT hand-maintained). This module embeds that generated data at
//! build time (`include_str!`) and serves it through `#[napi] op_impl`.
//!
//! Flow:
//!   bun scripts/select-native.ts --write   # auto-select → writes src/selection.json
//!   bun run build                          # embeds the selected decisions into the .node
//!   bun scripts/select-native.ts --check   # CI gate: fail on decisive drift
//!
//! Consumers read `opImpl(op)` ONCE at load time and bind each operation to a
//! fixed implementation (TS or native) — they do NOT swap underneath at runtime.

use std::collections::HashMap;
use std::sync::OnceLock;

use napi_derive::napi;

/// The generated benchmark data (see `src/selection.json`). Embedded at build
/// time so the `.node` ships the decisions without a runtime file read.
const SELECTION_JSON: &str = include_str!("../src/selection.json");

/// `op name → "native" | "js"`, parsed once from the generated JSON.
fn selection_map() -> &'static HashMap<String, String> {
    static MAP: OnceLock<HashMap<String, String>> = OnceLock::new();
    MAP.get_or_init(|| {
        let value: serde_json::Value =
            serde_json::from_str(SELECTION_JSON).expect("selection.json must be valid JSON");
        let mut map = HashMap::new();
        if let Some(ops) = value.get("ops").and_then(serde_json::Value::as_object) {
            for (op, decision) in ops {
                if let Some(impl_name) = decision.get("impl").and_then(serde_json::Value::as_str) {
                    map.insert(op.clone(), impl_name.to_string());
                }
            }
        }
        map
    })
}

/// The auto-selected native-vs-TS decision for `op`.
///
/// Returns `"native"` when the public API should back `op` with the Rust addon,
/// `"js"` when it should run the pure-TS implementation, or `None` for unknown
/// ops. The data comes from `src/selection.json` — generated by
/// `scripts/select-native.ts --write`, never hand-written here.
#[napi]
pub fn op_impl(op: String) -> Option<String> {
    selection_map().get(&op).cloned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn map_is_populated_from_generated_json() {
        let map = selection_map();
        assert!(!map.is_empty(), "selection.json must contain ops");
    }

    #[test]
    fn every_entry_is_native_or_js() {
        let map = selection_map();
        for (op, impl_name) in map {
            assert!(
                impl_name == "native" || impl_name == "js",
                "op {op} has invalid impl {impl_name}"
            );
        }
    }

    #[test]
    fn unknown_op_is_none() {
        assert_eq!(op_impl("doesNotExist".to_string()), None);
        assert_eq!(op_impl("".to_string()), None);
    }

    #[test]
    fn well_established_decisions_hold() {
        // These just pin the direction of the auto-selected data so a bad
        // regeneration is caught; the values themselves come from the bench.
        assert_eq!(op_impl("fnv1a64".to_string()).as_deref(), Some("native"));
        assert_eq!(op_impl("validateEmail".to_string()).as_deref(), Some("js"));
        assert_eq!(
            op_impl("gzipDecompress".to_string()).as_deref(),
            Some("native")
        );
    }
}
